package POM;
import BrowsersBase.BrowsersInvoked;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.*;
import org.testng.asserts.SoftAssert;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.PageFactory;

import BrowsersBase.BrowsersInvoked;
import CommonMethods.Helper;
import CommonMethods.PropertiesUtils;

public class CCPUtility extends Helper{
  
	public WebDriver driver;
	
	public CCPUtility(WebDriver driver) {
		super(driver);
		this.driver = driver;
		PageFactory.initElements(driver, this);	
	}
	
	
	
	  public static String cEOption = "//label[text()='Code Enforcement Case']";
	    public static String closeCDP = "div.case-details__close-icon img";
	    public static String cCPOption = "//label[text()='Code Enforcement Case']";
	    public static String createCaseButton = "//div/button[text()='Create Case']";
	    public static String assignCaseTo = "//h5[text()='Assign Case To']//parent::div//button";
	    public static String inspectionAssigneeTo = "//h5[text()='Assign Inspection To']//parent::div//button";
	    public static String createScheduleInspectionButton = "//div[@class='modal-footer']//button[2]";
	    public static String AddButton20 = "//div[@class='attachments-modal__footer']/button[2]";
	    public static String AddAttachmenttop = "//p[text()='Attachments']//preceding-sibling::button";
	    public static String AddAttachmentCCP = "//span[contains(text(),'Attachments')]//following-sibling::button";
	    public static String AddAttachmentbottom = "(//span[contains(text(),'Attachments')]//parent::h2//div//button)[2]";
	    public static String locationSearchField = "//div[@class='location-tile__inputs-container']//input";
	    public static String locationSearchResult = "//li[@id='react-autowhatever-1-section-0-item-0']";
	    public static String cRMOption = "//label[text()='Customer submission']";
	    public static String cCPTitle = "//h1[text()='Create A Case']";
	    public static String plusIconToCECRM = "//*[@class='app-header__new']";
	    public static String globalValidMsg = "//div[@class='create-case__global-error']";
	    public static String infoMsg = "//div[@class='location-tile__display-data-empty-message tile-empty-msg']";
	    public static String CCbutton = "//div/button[text()='Create Case']";
	    public static String Location = "//div[@class='location-tile__inputs-container']//input";
	    public static String Map = "//li[@id='react-autowhatever-1-section-0-item-0']";
	    public static String mapGis2 = "//div[@class='react-autosuggest-sections']//li//b";
	    public static String EditLocation = "//div[@class='edit-address__actions']/button";
	    public static String editStreetAddress = "//input[@name='streetAddress']";
	    public static String editCity = "//input[@name='city']";
	    public static String editZip = "//input[@name='zip']";
	    public static String saveButton = "//div[@class='edit-address__header']/child::div/button[2]";
	    public static String cancelButton = "//div[@class='edit-address__header']/child::div/button[1]";
	    public static String ToggleChecked = "//div[@class='react-toggle react-toggle--checked bs-toggle danger']";
	    public static String addLocManually = "//div[@class='react-autosuggest__function']";
	    public static String streetAdd = "//div[@class='manual-address-modal__body']//input[@name='streetAddress']";
	    public static String cityAdd = "//div[@class='manual-address-modal__body']//input[@name='city']";
	    public static String zipAdd = "//div[@class='manual-address-modal__body']//input[@name='zip']";
	    public static String saveButton2 = "//div[@class='manual-address-modal__footer']/button[2]";
	    public static String manualLocPopup = "(//div[@class='modal-header'])[2]";
	    public static String validationMsg3 = "//span[text()='The Address is required.']";
	    public static String apnAdd = "//div/input[@name='apn']";
	    public static String outAgencyMsg = "//div[contains(@class,'display-data--out-of-bounds')]//span";
	    public static String flagToggle = "(//div[@class='react-toggle-thumb'])[1]";
	    public static String cancelBtnLoc = "//div[@class='manual-address-modal__footer']/button[1]";

	    public static String streetLabel = "(//label[@class='field__label-data-field'])[1]";
	    public static String cityLabel = "(//label[@class='field__label-data-field'])[2]";
	    public static String zipLabel = "(//label[@class='field__label-data-field'])[4]";

	    public static String ZipLabel20 = "(//label[@class='field__label-data-field'])[5]";
	    public static String popupTitle = "(//div[@class='modal-header'])[2]";
	    public static String reasonToFlag = "//textarea[@name='reasonForFlagging']";
	    public static String flagAddressBtn = "//button[text()='Flag address']";
	    public static String crossIconFlag = "(//button[@class='square-btn btn btn-default'])[2]";
	    public static String flaggedLabel = "(//label[@class='field__label-data-field field__label-data-field--toggle'])[1]";
	    public static String violationsTile = "//div[@id='violation-tile']//h2/span";
	    public static String violationSearchBox = "//div/input[@placeholder=\"Start typing name of violation, article number or issue description\"]";
	    public static String violationList = "//div[@class=\"react-autosuggest__suggestion-element\"]/div";
	    public static String ViolationList20 = "//div[@class='icon-chooser']//preceding-sibling::div";
	    public static String violationPopup = "(//div[@class='modal-header'])[2]";
	    public static String entityField1 = "//div/input[@name='Animal Colour']";
	    public static String addButton = "//button[text()='Add']";
	    public static String validationMsg2 = "//p[@class='tile--error-msg']";
	    public static String infoMsg2 = "//div[@class='tile-empty-msg' and text()='You have not added any violations or issues yet.']";
	    public static String customIssue = "(//div[@class='react-autosuggest__function'])[2]";
	    public static String infoMsgNoSearch = "//div[@class='react-autosuggest__empty-message']";
	    public static String customIssueIcon = "(//div/i[@class='react-autosuggest__add-icon'])[2]";
	    public static String customIssueFeild = "//label[@class='field__label-label']";
	    public static String customIssueDesc = "//textarea[@name='issueDescription']/parent::div";
	    public static String validMsgCustom = "//span[@class='field__error']";
	    public static String waterViolation = "//label[@class='violation-tile__item-info-name']";
	    public static String validMsgVioPopup = "//div[@class='entity-modal__edit-error entity-modal__edit-error--show']";
	    public static String crossIconVio = "//div[@class='violation-tile__item-info']/following::button[1]";
	    public static String editIconVio = "(//button[@class='edit-btn  btn btn-primary'])[2]";
	    public static String uploadLink = "//label[@class='file-upload__label']";
	    public static String uploadLink2 = "//div[@class='file-upload__actions']//label[text()='Replace']";
	    public static String uploadedImg = "//div[@class='file-upload']/div/img";
	    public static String customIssueDlt = "//div[@id='violation-tile']/div[2]/div/div[2]/button";
	    public static String dltUploadedImg = "//div[@class='file-upload__actions']/button";
	    public static String entityAddBtn = "//div[@class='entity-modal__footer']/button[2]";
	    public static String entityCancelBtn = "//div[@class='entity-modal__footer']/button[1]";
	    public static String uploadedImgThumb = "//div[@class='entity-display-wrapper']/img";
	    public static String closePopup = "//button[text()='Close']";
	    public static String entitySearchBox = "//div[@class='searchbox-container']//input";
	    public static String entitySearchList = "//div[@class='list-label']";
	    public static String EntitySeachListCss = "ul li div.list-label";
	    public static String EntitySearchListB = "//div[@class='list-label']//b";
	    public static String EntitySearchList20 = "//ul[@class='react-autosuggest__suggestions-list']//div[@class='list-label']";
	    public static String addedVioList = "//label[@class='violation-tile__entity-info-label']";
	    public static String addAnotherVio = "//div[@class='violation-tile__entity-disclaimer']/a";
	    public static String countViolations = "//div[@id='violation-tile']/div/div/h2/span";
	    public static String countEachVio = "//div[@id='violation-tile']/div/div/h2/a[1]";
	    public static String addedImgThumb = "//div[@class='file-upload']//img";
	    public static String addContactFld = "//div[@class='contact-tile tile']//input";
	    public static String crtNewContact = "//div[@class='contact-tile tile']//div[@class='react-autosuggest__function']";
	    public static String contactPopup = "//div[@class='full-page-modal__header']/h1[text()='Create a Contact']";
	    public static String crtContactBtn = "(//div[@class='full-page-modal__header']//button[2])[2]";
	    public static String contactErrMsg = "(//span[@class='field__error'])[1]";
	    public static String nameField = "//input[@name='name']";
	    public static String violationsList = "//div[@class='react-autosuggest__suggestion-element']/div";
	    public static String addContactField = "//div[@class='contact-tile tile']//input";
	    public static String createNewContact = "//div[@class='contact-tile tile']//div[@class='react-autosuggest__function']";
	    public static String createContactBtn = "(//div[@class='full-page-modal__header']//button[2])[2]";
	    public static String createContactBtn2 = "(//div[@class='full-page-modal__header']//button[2])";
	    public static String countContact = "//div[@class='contact flex-row--center']";
	    public static String cancelContactBtn = "(//div[@class='full-page-modal__header']//button)[3]";
	    public static String editContact = "//div[@class='contact__actions']/button[1]";
	    public static String editContactPopup = "//div[@class='full-page-modal__header']/h1[text()='Edit Contact']";
	    public static String cancelEditPopup = "(//div[@class='full-page-modal__header']//button)[3]";
	    public static String deleteContact = "//div[@class='contact__actions']/button[2]";
	    public static String countContactTile = "//div[@class='contact-tile tile']//h2";
	    public static String createAnyway = "//div[@class='duplicate-contacts__footer']/button[2]";
	    public static String propertyOwnerOption = "//span/label[text()='Property Owner']";
	    public static String applyButton = "//button[text()='Apply']";
	    public static String emailField = "//input[@name='email']";
	    public static String workPhoneField = "//input[@name='workPhone']";
	    public static String imageIcon = "//span[text()='Attachments ']/following-sibling::button";
	    public static String attachmentTitle = "//div[@class='modal-header' and text()='Add Attachments']";
	    public static String cameraButton = "//label[@class='content-placeholder']";
	    public static String addButton2 = "//div[@class='attachments-modal__footer']/button[2]";
	    public static String imgThumb = "//img[@class='attachments-modal__saved-thumb']";
	    public static String crossIcon2 = "(//button[@class='close'])[2]";
	    public static String yesCloseBtn = "//div[@class='attachments-modal__footer']/button[1]";
	    public static String dontCloseBtn = "//div[@class='attachments-modal__footer']/button[2]";
	    public static String imgThumb2 = "//img[@class='attachments-tile__saved-thumb']";
	    public static String closeAttachmentTitle = "//div[@class='modal-header' and text()='Close Add Attachments']";
	    public static String attachmentDetailsTitle = "//div[@class='modal-header' and text()='Attachments Details']";
	    public static String modalHeaders = "//div[@class='modal-header']";
	    public static String addedImage = "//div[@class='attachments-tile__photo-container']/img";
	    public static String description = "//input[@name='description']";
	    public static String cancelBtnAttachDet = "//div[@class='attachments-edit__footer']/button[1]";
	    public static String updateBtn = "//div[@class='attachments-edit__footer']/button[2]";
	    public static String crossIcon = "//button[@class='delete-btn  btn btn-default']";
	    public static String countAttachment = "//div[@class='attachment-tile tile']//h2/span";
	    public static String deleteAttach = "//div[@class='attachments-edit__carousel']//button";
	    public static String yesDelete = "//div[@class='flex-row--middle']/button[2]";
	    public static String toasterMSGAttachment = "//div[text()='One/more files with unsupported format is/are discarded.']";
	    public static String toasterMSGSize = "//div[text()='File size cannot exceed 15MB']";
	    public static String uploadedImgTitle = "//div[@class='attachments-modal__saved-title']/span/b";
	    public static String uploadedImgName = "//input[@name='title']";
	    public static String uploadedImgLoc = "//input[@name='location']";
	    public static String imgTitleonCCP = "//a[@class='attachments-tile__photo-title']";
	    public static String imgDesconCCP = "//span[@class='clipped-text']";
	    public static String imgLoconCCP = "//label[@class='attachments-tile__photo-location']";
	    public static String createCasePop = "//div[@class='modal-header' and text()='Create Case']";
	    public static String checkboxPerIns = "//label[@for='PERFORM_INSPECTION']";
	    public static String checkboxSchIns = "//label[@for='SCHEDULE_INSPECTION']";
	    public static String crtSchInsButton = "//div[@class='modal-footer']//button[2]";
	    public static String nextInsSec = "//div[@class='inspection-details']";
	    public static String caseStatus = "//h2[@class='case-details__case-status']";
	    public static String totalContactsCDP = "//div[@class='contact flex-row--center']";
	    public static String totalViolationsCDP = "//div[@class='case-violation-list']";
	    public static String totalAttachmentsCDP = "//img[@class='attachments-tile__saved-thumb']";
	    public static String caseTilesCDP = "//div[@class='tile-header']//h2";
	    public static String assigneeTo = "//h5[text()='Assign Case To']//parent::div//button[@class='square-btn btn btn-primary']";
	    
	    
	    
	    
	    
	    public static By AssigneeTo = By.xpath(assigneeTo);
	    public static By CEOption = By.xpath(cEOption);
	    public static By CCPOption = By.xpath(cCPOption);
	    public static By CloseCDP  = By.cssSelector(closeCDP);
	    public static By CreateCaseButton = By.xpath(createCaseButton);
	    public static By AssignCaseTo = By.xpath(assignCaseTo);
	    public static By InspectionAssigneeTo = By.xpath(inspectionAssigneeTo);
	    public static By CreateScheduleInspectionButton = By.xpath(createScheduleInspectionButton);
	    public static By AddBtn = By.xpath(addButton);
	    public static By addAttachmenttop = By.xpath(AddAttachmenttop);
	    public static By addAttachmentCCP = By.xpath(AddAttachmentCCP);
	    public static By addAttachmentbottom = By.xpath(AddAttachmentbottom);
	    public static By LocationSearchField = By.xpath(locationSearchField);
	    public static By LocationSearchResult = By.xpath(locationSearchResult);
	    public static By CRMOption = By.xpath(cRMOption);
	    public static By CCPTitle = By.xpath(cCPTitle);
	    public static By PlusIconToCECRM = By.xpath(plusIconToCECRM);
	    public static By LocationFld = By.xpath(Location);
	    public static By InfoMsg = By.xpath(infoMsg);
	    public static By Map3 = By.xpath(Map);
	    public static By MapGis2 = By.xpath(mapGis2);
	    public static By EditLocIcon = By.xpath(EditLocation);
	    public static By EditStreetAdd = By.xpath(editStreetAddress);
	    public static By EditCity = By.xpath(editCity);
	    public static By EditZip = By.xpath(editZip);
	    public static By SaveButton = By.xpath(saveButton);
	    public static By CCButton = By.xpath(CCbutton);
	    public static By GlobalValidMsg = By.xpath(globalValidMsg);
	    public static By AddLocManually = By.xpath(addLocManually);
	    public static By ManualLocPopup = By.xpath(manualLocPopup);
	    public static By ValidationMsg3 = By.xpath(validationMsg3);
	    public static By SaveButton2 = By.xpath(saveButton2);
	    public static By StreetAdd = By.xpath(streetAdd);
	    public static By CityAdd = By.xpath(cityAdd);
	    public static By ZipAdd = By.xpath(zipAdd);
	    public static By ApnAdd = By.xpath(apnAdd);
	    public static By OutAgencyMsg = By.xpath(outAgencyMsg);
	    public static By CancelBtnLoc = By.xpath(cancelBtnLoc);
	    public static By StreetLabel = By.xpath(streetLabel);
	    public static By CityLabel = By.xpath(cityLabel);
	    public static By ZipLabel = By.xpath(zipLabel);
	    public static By zipLabel20 = By.xpath(ZipLabel20);
	    public static By CancelButton = By.xpath(cancelButton);
	    public static By toggleChecked = By.xpath(ToggleChecked);
	    public static By FlagToggle = By.xpath(flagToggle);
	    public static By PopupTitle = By.xpath(popupTitle);
	    public static By ReasonToFlag = By.xpath(reasonToFlag);
	    public static By FlagAddressBtn = By.xpath(flagAddressBtn);
	    public static By CrossIconFlag = By.xpath(crossIconFlag);
	    public static By FlaggedLabel = By.xpath(flaggedLabel);

	    public static By ViolationsTile = By.xpath(violationsTile);
	    public static By ViolationSearchBox = By.xpath(violationSearchBox);
	    public static By ViolationList = By.xpath(violationList);
	    public static By violationList20 = By.xpath(ViolationList20);
	    public static By ViolationPopup = By.xpath(violationPopup);
	    public static By EntityField1 = By.xpath(entityField1);
	    public static By AddButton = By.xpath(addButton);
	    public static By ValidationMsg2 = By.xpath(validationMsg2);
	    public static By InfoMsg2 = By.xpath(infoMsg2);
	    public static By InfoMsgNoSearch = By.xpath(infoMsgNoSearch);
	    public static By CustomIssueIcon = By.xpath(customIssueIcon);
	    public static By CustomIssueFeild = By.xpath(customIssueFeild);
	    public static By CustomIssueDesc = By.xpath(customIssueDesc);
	    public static By ValidMsgCustom = By.xpath(validMsgCustom);
	    public static By WaterViolation = By.xpath(waterViolation);
	    public static By ValidMsgVioPopup = By.xpath(validMsgVioPopup);
	    public static By EntitySearchBox = By.xpath(entitySearchBox);
	    public static By EntitySearchList = By.xpath(entitySearchList);
	    public static By entitySeachListCss = By.cssSelector(EntitySeachListCss);
	    public static By entitySearchListB = By.xpath(EntitySearchListB);
	    public static By entitySearchList20 = By.xpath(EntitySearchList20);
	    public static By AddedVioList = By.xpath(addedVioList);
	    public static By AddAnotherVio = By.xpath(addAnotherVio);
	    public static By CrossIconVio = By.xpath(crossIconVio);
	    public static By EditIconVio = By.xpath(editIconVio);
	    public static By UploadLink = By.xpath(uploadLink);
	    public static By UploadLink2 = By.xpath(uploadLink2);
	    public static By UploadedImg = By.xpath(uploadedImg);
	    public static By CustomIssueDlt = By.xpath(customIssueDlt);
	    public static By DltUploadedImg = By.xpath(dltUploadedImg);
	    public static By EntityAddBtn = By.xpath(entityAddBtn);
	    public static By EntityCancelBtn = By.xpath(entityCancelBtn);
	    public static By UploadedImgThumb = By.xpath(uploadedImgThumb);
	    public static By CountViolations = By.xpath(countViolations);
	    public static By CountEachVio = By.xpath(countEachVio);
	    public static By ClosePopup = By.xpath(closePopup);
	    public static By AddedImgThumb = By.xpath(addedImgThumb);

	    public static By AddContactFld = By.xpath(addContactFld);
	    public static By CrtNewContact = By.xpath(crtNewContact);
	    public static By ContactPopup = By.xpath(contactPopup);
	    public static By CrtContactBtn = By.xpath(crtContactBtn);
	    public static By ContactErrMsg = By.xpath(contactErrMsg);
	    public static By NameField = By.xpath(nameField);
	    public static By CreateContactBtn = By.xpath(createContactBtn);
	    public static By CreateContactBtn2 = By.xpath(createContactBtn2);
	    public static By ViolationsList = By.xpath(violationsList);
	    public static By AddContactField = By.xpath(addContactField);
	    public static By CreateNewContact = By.xpath(createNewContact);
	    public static By CountContact = By.xpath(countContact);
	    public static By CancelContactBtn = By.xpath(cancelContactBtn);
	    public static By EditContact = By.xpath(editContact);
	    public static By EditContactPopup = By.xpath(editContactPopup);
	    public static By CancelEditPopup = By.xpath(cancelEditPopup);
	    public static By DeleteContact = By.xpath(deleteContact);
	    public static By CountContactTile = By.xpath(countContactTile);
	    public static By CreateAnyway = By.xpath(createAnyway);
	    public static By PropertyOwnerOption = By.xpath(propertyOwnerOption);
	    public static By ApplyButton = By.xpath(applyButton);
	    public static By EmailField = By.xpath(emailField);
	    public static By WorkPhoneField = By.xpath(workPhoneField);

	    public static By ImageIcon = By.xpath(imageIcon);
	    public static By AttachmentTitle = By.xpath(attachmentTitle);
	    public static By CameraButton = By.xpath(cameraButton);
	    public static By AddButton2 = By.xpath(addButton2);
	    public static By ImgThumb = By.xpath(imgThumb);
	    public static By CrossIcon2 = By.xpath(crossIcon2);
	    public static By YesCloseBtn = By.xpath(yesCloseBtn);
	    public static By DontCloseBtn = By.xpath(dontCloseBtn);
	    public static By ImgThumb2 = By.xpath(imgThumb2);
	    public static By CloseAttachmentTitle = By.xpath(closeAttachmentTitle);
	    public static By ModalHeaders = By.xpath(modalHeaders);
	    public static By AddedImage = By.xpath(addedImage);
	    public static By Description = By.xpath(description);
	    public static By CancelBtnAttachDet = By.xpath(cancelBtnAttachDet);
	    public static By UpdateBtn = By.xpath(updateBtn);
	    public static By CrossIcon = By.xpath(crossIcon);
	    public static By CountAttachment = By.xpath(countAttachment);
	    public static By DeleteAttach = By.xpath(deleteAttach);
	    public static By YesDelete = By.xpath(yesDelete);
	    public static By AttachmentDetailsTitle = By.xpath(attachmentDetailsTitle);
	    public static By UploadedImgName = By.xpath(attachmentDetailsTitle);

	    public static By ToasterMSGAttachment = By.xpath(toasterMSGAttachment);
	    public static By ToasterMSGSize = By.xpath(toasterMSGSize);
	    public static By UploadedImgTitle = By.xpath(uploadedImgTitle);
	    public static By UploadedImgNameA = By.xpath(uploadedImgName);
	    public static By UploadedImgLoc = By.xpath(uploadedImgLoc);
	    public static By ImgTitleonCCP = By.xpath(imgTitleonCCP);
	    public static By ImgDesconCCP = By.xpath(imgDesconCCP);
	    public static By ImgLoconCCP = By.xpath(imgLoconCCP);

	    public static By CreateCasePop = By.xpath(createCasePop);
	    public static By CheckboxPerIns = By.xpath(checkboxPerIns);
	    public static By CheckboxSchIns = By.xpath(checkboxSchIns);
	    public static By CrtSchInsButton = By.xpath(crtSchInsButton);
	    public static By NextInsSec = By.xpath(nextInsSec);
	    public static By CaseStatus = By.xpath(caseStatus);
	    public static By TotalContactsCDP = By.xpath(totalContactsCDP);
	    public static By TotalViolationsCDP = By.xpath(totalViolationsCDP);
	    public static By TotalAttachmentsCDP = By.xpath(totalAttachmentsCDP);
	    public static By CaseTilesCDP = By.xpath(caseTilesCDP);

	    public static SoftAssert softAssert = new SoftAssert();


	    public static String searchLocationKey1O = PropertiesUtils.getPropertyValue("searchLocationKey1O");
	    public static String searchLocationKey = PropertiesUtils.getPropertyValue("searchLocationKey");
	
	

}
